name: Health Check

on:
    push:
        branches:
        - master
    pull_request:
        branches: [ master ]
        types: [ opened, synchronize ]

jobs:
    health_check:
        runs-on: ubuntu-latest
        steps:
          - name: Check health
            uses: jtalk/url-health-check-action@v2
            with:
                url: https://mibkr-pokemon-app.herokuapp.com/health
                max-attempts: 3 # Optional, defaults to 1
                retry-delay: 5s # Optional, only applicable to max-attempts > 1